---
broadcast:
  - "abc"
  - "abc"

luckyrewards: []

join:
  - "&l&e=================="
  - ""
  - "&l&fＬＯＣＭ &bＰＲＩＳＯＮ"
  - ""
  - "&l&epri.locmvn.net"
  - ""
  - "&l&e==================="

first-join:
  - "&l&e=================="
  - ""
  - "&l&fＬＯＣＭ &bＰＲＩＳＯＮ"
  - ""
  - "&l&epri.locmvn.net"
  - ""
  - "&l&d/lcoin&f để xem cách thức donate"
  - "&l&d/mine&f để vào khu mỏ"
  - ""
  - "&l&e==================="
...